@echo off
echo Starting Tango Master Dev Server...
start /b npm run dev
echo Waiting for server to initialize...
timeout /t 5 /nobreak > nul
echo Opening browser...
start http://localhost:3000
echo.
echo Press any key to stop the app OR Press q + enter to quit...
pause > nul
taskkill /f /im node.exe > nul
